before_script:
  - echo "hello gitlab ci"

stages:
  - install
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - dist

install_job:
  stage: install
  only:
    - develop
  script:
    - echo 'install ...'
    - npm install
  tags:
    - gitlab-runner-fe-tag-v.1.0

build_job:
  stage: build
  only:
    - develop
  script:
    - echo 'build ...'
    - npm run build
  tags:
    - gitlab-runner-fe-tag-v.1.0

deploy_job:
  stage: deploy
  only:
    - develop
  script:
    - echo 'deploy ...'
    - cd dist
    - scp -r ./* D:/gitlab-runner/nginx-1.16.0/runner/fe
  tags:
    - gitlab-runner-fe-tag-v.1.0
