before_script: # 定义在job执行之前的执行脚本(就一次)
  - echo "hello gitlab ci"

stages:
  - install
  - start

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install
  only:
    - develop
  artifacts:
    paths:
      - node_modules/
  tags:
    - gitlab-runner-fe-tag-v.1.0

job-start:
  stage: start
  script:
    - npm run start
  only:
    - develop
  tags:
    - gitlab-runner-fe-tag-v.1.0
