language: node_js
node_js:
  - '10'
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
install: yarn
script:
  - yarn run build
addons:
  ssh_known_hosts:
    - 58.87.121.239:22

before_install:
  - openssl aes-256-cbc -K $encrypted_65f6a220a07e_key -iv $encrypted_65f6a220a07e_iv
    -in travis.enc -out ~\/.ssh/travis -d

after_success:
  - ssh ubuntu@58.87.121.239 -o StrictHostKeyChecking=no 'echo "haha haha"'
