language: node_js
node_js:
  - '10'

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_65f6a220a07e_key -iv $encrypted_65f6a220a07e_iv
    -in travis.enc -out ~/.ssh/travis -d
  - chmod 600 ~/.ssh/travis

addons:
  ssh_known_hosts: "$IP"

branches:
  only:
    - master

install: yarn

script:
  - yarn run build

after_script:
  - pwd
  - scp -o StrictHostKeyChecking=no -r dist/ ubuntu@$IP:/var/www/html/myantdpro
